#! /usr/bin/env python
# encoding: utf-8

obj = bld.create_obj('cc', 'program')
obj.find_sources_in_dirs('.')
obj.includes='.'
obj.uselib='GTK GDK PANGO GOBJECT PCRE'
obj.target='switch2'

install_files('DATADIR', 'gtk-theme-switch-ex', 'ui_main.xml')

